name: hey # you probably want to 'snapcraft register <name>'
version: '0' # just for humans, typically '1.2+git' or '1.3.2'
summary: HTTP load generator, ApacheBench (ab) replacement, formerly rakyll/boom
description: |
  hey is a tiny program that sends some load to a web application.
  hey was originally called boom and was influenced from Tarek Ziade's tool at
  tarekziade/boom. Using the same name was a mistake as it resulted in cases
  where binary name conflicts created confusion. To preserve the name for its
  original owner, we renamed this project to hey.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  hey:
    command: hey
    plugs:
      - network

parts:
  go17:
    plugin: x-gobuild
    build-packages: [golang-go]
    source: https://go.googlesource.com/go
    source-type: git
    source-tag: go1.7.5
    prime:
      - -*
  hey:
    plugin: go
    after: [go17]
    source: .
    source-type: git
    go-importpath: github.com/rakyll/hey
