on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-buster
      volumes:
        - "/home/runner/work/$GITHUB_REPOSITORY:/go/src/github.com/$GITHUB_REPOSITORY"
    steps:
      - uses: actions/checkout@v1

      - name: restore from cache
        uses: actions/cache@v1
        with:
          path: /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: build
        run: |
          go install github.com/mitchellh/gox
          make build

      - name: compress build binary
        run: |
          tar -czvf dist.tar.gz hey

      - name: upload compressed dist to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: distribution
          path: dist.tar.gz

  docker:
    name: docker
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v1

      - name: downloads compressed dist
        uses: actions/download-artifact@v1
        with:
          name: distribution

      - name: untar dist.tar.gz
        run: |
          tar -xzvf distribution/dist.tar.gz
          rm -rf distribution/

      - name: build docker image
        run: |
          docker build . --file Dockerfile --tag $(dirname $GITHUB_REPOSITORY)/$(basename $GITHUB_REPOSITORY)
          docker tag $(dirname $GITHUB_REPOSITORY)/$(basename $GITHUB_REPOSITORY) $(dirname $GITHUB_REPOSITORY)/$(basename $GITHUB_REPOSITORY):${{ github.sha }}

      - name: log into docker registry
        run: echo "${{ secrets.DOCKER_PSW }}" | docker login -u ${{ secrets.DOCKER_USR }} --password-stdin

      - name: push image to docker registry
        run: |
          # pushes unique commit sha based tag
          docker push $(dirname $GITHUB_REPOSITORY)/$(basename $GITHUB_REPOSITORY)
          docker push $(dirname $GITHUB_REPOSITORY)/$(basename $GITHUB_REPOSITORY):${{ github.sha }}
