name: Update Codecov

on:
  workflow_dispatch:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '**/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  update-codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: Run coverage
        # TODO: add the -race flag, and fix the error
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          file: coverage.txt
